import 'package:emotivision/screens/reusable_ideas_screen.dart';
import 'package:emotivision/utils/app_colors.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart'; // For Clipboard
import 'package:google_fonts/google_fonts.dart';
import 'package:lottie/lottie.dart';

// lib/screens/story_creation_screen.dart
// This screen displays the story generated by the Gemini API for a detected object.
// It also provides an option to navigate to see reusable ideas for the object.

class StoryCreationScreen extends StatefulWidget {
  final String objectLabel;
  final String story;
  final String emotion; // The emotion used to generate the story

  const StoryCreationScreen({
    super.key,
    required this.objectLabel,
    required this.story,
    required this.emotion,
  });

  @override
  State<StoryCreationScreen> createState() => _StoryCreationScreenState();
}

class _StoryCreationScreenState extends State<StoryCreationScreen> with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double> _cardAnim;
  late Animation<double> _buttonAnim;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 900),
    );
    _cardAnim = CurvedAnimation(parent: _controller, curve: Curves.easeOutBack);
    _buttonAnim = CurvedAnimation(parent: _controller, curve: const Interval(0.5, 1.0, curve: Curves.easeOutBack));
    _controller.forward();
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      backgroundColor: const Color(0xFFE3F6FD),
      body: SafeArea(
        child: SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 18.0, vertical: 10),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.center,
              children: [
                // Lottie sparkle/confetti animation at the top
                Lottie.asset(
                  'assets/animations/sparkle.json',
                  height: 120,
                  repeat: true,
                  fit: BoxFit.contain,
                ),
                const SizedBox(height: 8),
                // Step title
                Text(
                  'Step 2: The ',
                  style: GoogleFonts.fredoka(
                    fontSize: 20,
                    color: Colors.grey[700],
                  ),
                ),
                RichText(
                  text: TextSpan(
                    style: GoogleFonts.fredoka(
                      fontSize: 20,
                      color: Colors.grey[700],
                    ),
                    children: const [
                      TextSpan(text: 'Magical '),
                      TextSpan(text: 'Story', style: TextStyle(color: Color(0xFF3DDC97))),
                      TextSpan(text: ' Unfolds...'),
                    ],
                  ),
                ),
                const SizedBox(height: 10),
                // Big playful heading
                Text(
                  '📖 The Tale of the "${widget.objectLabel}"',
                  textAlign: TextAlign.center,
                  style: GoogleFonts.fredoka(
                    fontSize: 32,
                    color: AppColors.primaryOrange,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 10),
                // Animated story card
                ScaleTransition(
                  scale: _cardAnim,
                  child: Container(
                    margin: const EdgeInsets.symmetric(vertical: 10),
                    padding: const EdgeInsets.all(20),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(24),
                      boxShadow: [
                        BoxShadow(
                          color: AppColors.primaryOrange.withOpacity(0.13),
                          blurRadius: 16,
                          offset: const Offset(0, 8),
                        ),
                      ],
                      border: Border.all(color: AppColors.primaryOrange.withOpacity(0.18), width: 2),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          children: [
                            const Icon(Icons.auto_stories, color: AppColors.primaryOrange, size: 28),
                            const SizedBox(width: 8),
                            Text(
                              'Story of the "${widget.objectLabel}"',
                              style: GoogleFonts.fredoka(
                                fontSize: 20,
                                color: AppColors.primaryOrange,
                              ),
                            ),
                            const Spacer(),
                            IconButton(
                              icon: const Icon(Icons.copy_all_outlined, color: AppColors.secondaryText),
                              tooltip: "Copy Story",
                              onPressed: () {
                                Clipboard.setData(ClipboardData(text: widget.story));
                                ScaffoldMessenger.of(context).showSnackBar(
                                  const SnackBar(content: Text('Story copied to clipboard!')),
                                );
                              },
                            ),
                          ],
                        ),
                        const SizedBox(height: 10),
                        Container(
                          padding: const EdgeInsets.all(16.0),
                          decoration: BoxDecoration(
                            color: const Color(0xFFE8F9E4),
                            borderRadius: BorderRadius.circular(16.0),
                            border: Border.all(color: AppColors.primaryGreen.withOpacity(0.3)),
                          ),
                          child: Text(
                            widget.story,
                            textAlign: TextAlign.justify,
                            style: GoogleFonts.comicNeue(
                              fontSize: 18,
                              color: AppColors.secondaryText,
                              height: 1.6,
                              fontWeight: FontWeight.w500,
                            ),
                          ),
                        ),
                        const SizedBox(height: 16),
                        Row(
                          children: [
                            const Icon(Icons.emoji_emotions, color: Color(0xFF3DDC97)),
                            const SizedBox(width: 6),
                            Text(
                              'Evoked Feeling: ',
                              style: GoogleFonts.fredoka(
                                fontSize: 16,
                                color: Colors.grey[700],
                              ),
                            ),
                            Text(
                              widget.emotion,
                              style: GoogleFonts.fredoka(
                                fontSize: 16,
                                color: Color(0xFF3DDC97),
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 30),
                // Animated button
                ScaleTransition(
                  scale: _buttonAnim,
                  child: ElevatedButton.icon(
                    icon: const Icon(Icons.recycling_outlined, color: Colors.white),
                    label: Text(
                      'What Else Can It Be?',
                      style: GoogleFonts.fredoka(fontSize: 20),
                    ),
                    onPressed: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) => ReusableIdeasScreen(objectLabel: widget.objectLabel),
                        ),
                      );
                    },
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.primaryOrange,
                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 18),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(30.0),
                      ),
                      elevation: 8,
                      shadowColor: AppColors.primaryOrange.withOpacity(0.3),
                    ),
                  ),
                ),
                const SizedBox(height: 20),
                // Back button
                TextButton.icon(
                  icon: const Icon(Icons.arrow_back, color: AppColors.primaryOrange),
                  label: Text(
                    'Back to Discover',
                    style: GoogleFonts.fredoka(
                      color: AppColors.primaryOrange,
                      fontSize: 16,
                    ),
                  ),
                  onPressed: () => Navigator.pop(context),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
